import type { Stage } from './types'

export const FAKE_EMAIL_DOMAIN = 'wcpred.local'

export function usernameToEmail(username: string): string {
  return `${username.toLowerCase().trim()}@${FAKE_EMAIL_DOMAIN}`
}

export const STAGE_POINTS: Record<Stage, number> = {
  group: 50,
  round_of_32: 75,
  round_of_16: 100,
  quarter_final: 125,
  semi_final: 150,
  third_place: 175,
  final: 175,
}

export const TOURNAMENT_WINNER_POINTS = 250

export const STAGE_LABELS: Record<Stage, string> = {
  group: 'Group Stage',
  round_of_32: 'Round of 32',
  round_of_16: 'Round of 16',
  quarter_final: 'Quarter-finals',
  semi_final: 'Semi-finals',
  third_place: 'Third Place',
  final: 'Final',
}

export const STAGE_ORDER: Stage[] = [
  'group',
  'round_of_32',
  'round_of_16',
  'quarter_final',
  'semi_final',
  'third_place',
  'final',
]

export const TEAM_FLAGS: Record<string, string> = {
  'Mexico': '🇲🇽',
  'South Africa': '🇿🇦',
  'Canada': '🇨🇦',
  'Brazil': '🇧🇷',
  'Italy': '🇮🇹',
  'Argentina': '🇦🇷',
  'Germany': '🇩🇪',
  'France': '🇫🇷',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Spain': '🇪🇸',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Croatia': '🇭🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Australia': '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  'Iran': '🇮🇷',
  'Qatar': '🇶🇦',
  'United States': '🇺🇸',
  'USA': '🇺🇸',
  'Ecuador': '🇪🇨',
  'Senegal': '🇸🇳',
  'Morocco': '🇲🇦',
  'Tunisia': '🇹🇳',
  'Nigeria': '🇳🇬',
  'Cameroon': '🇨🇲',
  'Ghana': '🇬🇭',
  'Egypt': '🇪🇬',
  'Algeria': '🇩🇿',
  'Serbia': '🇷🇸',
  'Switzerland': '🇨🇭',
  'Denmark': '🇩🇰',
  'Poland': '🇵🇱',
  'Sweden': '🇸🇪',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Republic of Ireland': '🇮🇪',
  'Norway': '🇳🇴',
  'Austria': '🇦🇹',
  'Czech Republic': '🇨🇿',
  'Türkiye': '🇹🇷',
  'Turkey': '🇹🇷',
  'Ukraine': '🇺🇦',
  'Russia': '🇷🇺',
  'Paraguay': '🇵🇾',
  'Peru': '🇵🇪',
  'Chile': '🇨🇱',
  'Venezuela': '🇻🇪',
  'Bolivia': '🇧🇴',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Panama': '🇵🇦',
  'El Salvador': '🇸🇻',
  'Trinidad and Tobago': '🇹🇹',
  'Indonesia': '🇮🇩',
  'China PR': '🇨🇳',
  'Uzbekistan': '🇺🇿',
  'Iraq': '🇮🇶',
  'Palestine': '🇵🇸',
  'Bahrain': '🇧🇭',
  'Jordan': '🇯🇴',
  'Haiti': '🇭🇹',
  'Bosnia & Herzegovina': '🇧🇦',
  'Cape Verde': '🇨🇻',
  'Curaçao': '🇨🇼',
  'Ivory Coast': '🇨🇮',
  'New Zealand': '🇳🇿',
  'Slovenia': '🇸🇮',
  'Albania': '🇦🇱',
  'Romania': '🇷🇴',
  'Hungary': '🇭🇺',
  'Slovakia': '🇸🇰',
  'Georgia': '🇬🇪',
  'Finland': '🇫🇮',
  'Iceland': '🇮🇸',
  'Greece': '🇬🇷',
  'Kenya': '🇰🇪',
  'Zimbabwe': '🇿🇼',
  'DR Congo': '🇨🇩',
  'Mali': '🇲🇱',
  'Burkina Faso': '🇧🇫',
  'Tanzania': '🇹🇿',
  'Mozambique': '🇲🇿',
  'Comoros': '🇰🇲',
  'Uganda': '🇺🇬',
  'Botswana': '🇧🇼',
  'Sudan': '🇸🇩',
  'Benin': '🇧🇯',
}

export function getFlag(team: string): string {
  return TEAM_FLAGS[team] || '🏳️'
}
